version: '3.7'
services:
  client:
    stdin_open: true
    container_name: client
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - api
  api:
    container_name: api
    restart: always
    build: ./api
    ports:
      - '5000:5000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'